# globals
global:
  # python module `secrets.token_urlsafe()`
  JWT_KEY: ZSCmULXCSvFBZp9MGq7iHIqBS017fpk7nFRWsbUXo0Y
# environments
production: &default
  db:
    mysql:
      host: mysql
      port: 3306
      db: cloud_img
      user: root
      password:
      minsize: 10
      maxsize: 100
    redis:
      host: redis
      port: 6379
      db: 0
      password:

debug:
  <<: *default

test:
  db:
    mysql:
      host: mysql
      port: 3306
      db: cloud_img
      user: root
      password:
      minsize: 10
      maxsize: 100
    redis:
      host: redis
      port: 6379
      db: 0
      password:
